image: node:10.15.3

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - setup
  # - test
  - build

setup:
  stage: setup
  script:
    - npm install -g @angular/cli
    - npm ci
  only:
    - master

# test:
#   stage: test
#   script:
#     - npm run test
#   only:
#     - master

build:
  stage: build
  script:
    - npx ng build --prod
  artifacts:
    paths:
      - dist
  only:
    - master
