
export const WALLET_SERVICES_HTTP_BACKEND_URL               = Symbol('WALLET_SERVICES_HTTP_BACKEND_URL');

export const WALLET_SERVICES_HTTP_BACKEND_CONTROLLER_API    = Symbol('WALLET_SERVICES_HTTP_BACKEND_CONTROLLER_API');
export const WALLET_SERVICES_HTTP_BACKEND_CONTROLLER_PREFIX = Symbol('WALLET_SERVICES_HTTP_BACKEND_CONTROLLER_PREFIX');

export const WALLET_SERVICES_SESSION_STORAGE                = Symbol('WALLET_SERVICES_SESSION_STORAGE');
